apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-rs
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: nginx-pod
      labels:
       env: production
    spec:
      containers:
      - name: nginx-container
        image: nginx
      